FLAGS = -Wall -Wextra -Werror
PART1 = ./Partie_1
PART2 = ./Partie_2

#Your Makefile must at least contain the rules $(NAME), all, clean, fclean and re.
$(NAME):

all:
	gcc $(FLAGS) $(PART1)/%.c $(PART2)/%.c -I libft.h

clean:

fclean:

re: